# Generated by Django 5.2.4 on 2025-09-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_customer_remove_user_is_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('order_placed', 'Order Placed'), ('failed', 'Failed')], default='pending', max_length=15),
        ),
    ]
