# Generated by Django 5.2.4 on 2025-08-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
    ]
